### ISSUE TITLE
Got infeasible optimal solution

### ISSUE THREAD

**Issue by KenZhenLin** [oxfordcontrol/TRS.jl#6]
Hi! The code is very helpful! Sometimes the solution returned by trs is infeasible. In my following example shown in the pictures below, the function returned an optimal solution whose norm was much larger than the trust region radius r. Could you please help me see what went wrong? Thanks!
<img width="661" alt="TRS1" src="https://user-images.githubusercontent.com/56413662/69931183-45fac880-1494-11ea-96d4-67b9685a3939.png">
<img width="270" alt="TRS2" src="https://user-images.githubusercontent.com/56413662/69931186-498e4f80-1494-11ea-920d-cdd46a9f20e7.png">
<img width="675" alt="TRS3" src="https://user-images.githubusercontent.com/56413662/69931188-4dba6d00-1494-11ea-9c9a-baa1ff68a1fa.png">

**Comment by goulart-paul** [comment]
I can't see every entry of 'P' and 'q', but both appear to have incredibly small norm.   Possibly you are having some machine precision related error.  

What happens if you scale up `P` and `q` to be something of roughly unit norm?

If that does not fix the issue then I suggest posting code with a fully specified MWE so we can try it out.

**Comment by KenZhenLin** [comment]
Thanks! I will try it out. 
By the way, is any one of the column of the output x  (x, info = trs(P,q,r)) has higher priority than the other columns? 
Also, you claim that there could be local-no-global minimizer with objective value less than the one of the global. I can't see how you define such local minimizer in the standard TRS. Shouldn't we only have global solutions in the standard TRS?

**Comment by nrontsis** [comment]
If `P` is positive semidefinite then the `trs` problem is convex and it does not have local-nonglobal minimizers. Otherwise (i.e. when P is indefinite or you solve the `trs_boundary` problem) a local-nonglobal minimizer might exist. You could find details about the minimisers of the `trs` [here](https://arxiv.org/pdf/1906.04022.pdf) (Theorem 2, and in general the whole of Section 2, including the references therein).

How do you mean "higher priority"?

**Comment by KenZhenLin** [comment]
Thanks!
If we only have the constraint ||x||<=r ,as in the standrad TRS, then your function trs can always find an global minimum, right? In this case, how is it possible that there will be a local-nonglobal minimizer with objective value less than the one of the global? Shouldn't the global solution has the lowest objective value?

By "higher priority", I mean does the order of the columns matter? Is the solution in the first column better than the one in the second column in some sense? Or I can simply use any one of the columns as a global optimal solution?

**Comment by nrontsis** [comment]
> If we only have the constraint ||x||<=r ,as in the standrad TRS, then your function trs can always find an global minimum, right?

Yes.
> In this case, how is it possible that there will be a local-nonglobal minimizer with objective value less than the one of the global? Shouldn't the global solution has the lowest objective value?

Please refer to the references of my previous answer.
> By "higher priority", I mean does the order of the columns matter? Is the solution in the first column better than the one in the second column in some sense? Or I can simply use any one of the columns as a global optimal solution?

Yes, in the README.md I say:
> The global minimizers(s) proceed the local one.

The first column is always "guaranteed" to be a global minimiser, while the second column might simply be a local minimiser.

**Comment by KenZhenLin** [comment]
I tried to normalize the input matrix and vector. It seems to fix the problem, but here are some new issues. I would appreciate it if you could give some suggestions. Please check out the following code.

`using TRS

idx2 = [1,7,11,12,14,17,20,21,22,24,29,38,53,70,77,80,89,91,97]
elem = [0.2351107800575678 
 0.24349415700371638
 0.22217940791343302
 0.23078636688574108
 0.2246245847966884 
 0.21746869560094179
 0.23857631481232688
 0.22439077637865232
 0.2237682711839482 
 0.2176987238291504 
 0.23935066912796457
 0.23058508291039598
 0.21821037708244043
 0.23572472293901975
 0.2262445932414506 
 0.21927703514681898
 0.23450603307126824
 0.2392385811216474 
 0.23491794555304188]

Bt = zeros(100,100)
qt = zeros(100)
rt = 4.000000000000001
for k in 1:length(idx2)
    Bt[idx2[k],idx2[k]] = elem[k]
end

pt, infot = trs(Bt, qt, rt)`

Here Bt is a diagonal matrix with nonzero entries specified in the vector elem and the corresponding indices in idx2. The norm of Bt is close to 1 and qt is the zero vector. If I run this code multiple times, the output global optimal solution pt can sometimes be a vector of NaN. Please see the following pictures for examples of output:

<img width="630" alt="trstrs1" src="https://user-images.githubusercontent.com/56413662/70578363-7f5dc300-1b7b-11ea-8c53-81059295bb67.png">

<img width="1068" alt="trstrs2" src="https://user-images.githubusercontent.com/56413662/70578690-8802c900-1b7c-11ea-9f4d-c6e9329f6d5d.png">


As you can see from the pictures, The NaN output is not always the case, though. But if you try running this code more than 5 times, this issue is very likely to occur.

**Comment by nrontsis** [comment]
Thanks for reporting this. I believe that 8be02b3 fixes this, hence I have closed the issue. Feel free to reopen if you still experience issues.

**Comment by KenZhenLin** [comment]
Thanks for fixing the issue! Regarding the local-non-global minimizer, I read the reference, and there is one thing that is not clear to me. You claim "TRS can exhibit at most one local minimizer with objective value less than the one of the global." By definition, the global minimizer should have the lowest objective value, right? How can it be "global" if there is another solution with a lower objective value?

**Comment by goulart-paul** [comment]
It is a typoI think, or perhaps just badly explained.    There will be a global minimizer, plus at most one other point that is a local minimiser somewhere.   If there is such a point it will have a worse (i.e. higher, if minimizing) value than the global minimizer.
